github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://github.com/iRed-Github', 'https://github.com/Kamakshi-Sinha', 'https://dsc.gg/idk-development', 'https://dsc.gg/pcg-empire', 'https://top.gg/bot/977141223301189674']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
